# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b36e63a2a389da770ee8dc0eee0fe24da35d416dc4f6cdf87b9857bb57fab511a51e08ab2823b3aa78122c19d9a0360d078f4f40bd45b920a48ce39b04ddcf61

test:
  secret_key_base: d6a6dd4b4d2dcacb59e5ff6c4e9af87c258b84248e91ba7e66b9fcd1a044c639778a8b91436320c5fee188f0b6dbdc8ac7614ad9d52c21b7e2a0b6748f29b1ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
